name: atoms-bundling

on: push

jobs:
  storybook-deploy:
    name: Deploy storybook
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn

      - name: Bootstrapping
        run: npx lerna bootstrap

      - name: Push code
        run: npm run deploy:storybook
